#!/usr/bin/env bash
# This script is displaying numbers from 1 - 20

svteen="bad luck from Italy"
four="bad luck from China"
nine="bad luck from Japan"
i=1

while((i <= 20)); do
    case $i in
        4)
            echo $i
            echo $four
            ;;
        9)
            echo $i
            echo $nine
            ;;
        17)
            echo $i
            echo $svteen
            ;;
        *)
            echo $i
    esac
    ((i++))
done