#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

to_print="Hour: "
i=0
j=1


while((i <= 12)); do
    echo "${to_print}${i}"
    while((j <= 59)); do
        echo "${j}"
        ((j++))
    done
    ((i++))
    j=1
done
