#!/usr/bin/env bash
# This script gives info about school

if [ -e "$school" ]; then
    echo "school file exists"
    if [ -s "$file_path" ]; then
        echo "school file is not empty"
        if [ -f "$file_path" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
